services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/data/audiobooks:/audiobooks
      - ./config:/config
      - /mnt/data/audiobooks:/metadata
    environment:
      - TZ=America/Los_Angeles
