---
services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
       - SLSKD_REMOTE_CONFIGURATION=true
       - SLSKD_USERNAME=${ADMIN_USER}
       - SLSKD_PASSWORD=${ADMIN_PASS}
       - SLSKD_SLSK_USERNAME=${SLSK_USER}
       - SLSKD_SLSK_PASSWORD=${SLSK_PASS}
    volumes:
      - /mnt/data/soulseek_downloads:/app/downloads:rw
      - /mnt/data/slskd_config:/app:rw
      - /mnt/data/music:/music:rw
      - /mnt/data/video:/video:rw
    user: 1000:1000
    restart: always
